### ISSUE TITLE
User Auth

### ISSUE THREAD

**Issue by carlosaicrag** [albertyee84/TrackMania#3]
# User Auth

## Functionality

- [x] The main button with logo should link to `/`
- [x] Has working demo login
- [x] Smooth, bug free navigation

### Before Login

- [x] The `/login` page should not display a link to `Log In`. Same for `/signup`
- [x] Going to a random route `/#/oweiniouewbrviuwebv` should redirect or display a 404 page
- [x] Errors should display for both `/signup` and `/login`.
- [x] Errors should clear when moving between `/signup` and `/login`.
- [x] Can sign up a user
- [x] Can sign in as a user
- [x] Can log out a user
- [x] Can't sign up with the same username/email
- [x] Pressing enter after filling out the session form should use the form data, not the demo user

### After Login

- [x] Should not be able to visit `/login` or `/signup`
- [x] Should be able to refresh the page and still be logged in

## Style

- [ ] The site should look exactly like the actual site
- [x] All relevant elements should have `cursor: pointer` on hover
- [x] When errors are displayed, most elements should not move around the page (particularly input boxes)
- [x] Remove Redux logger and all console.log()'s from production

## Seeds
- [x] Adequate and appropriate seeds

**Comment by carlosaicrag** [comment]
<img width="1124" alt="Screen Shot 2019-11-12 at 11 51 48 AM" src="https://user-images.githubusercontent.com/30717440/68705604-34806980-0543-11ea-865c-d6523d33d640.png">
make background for this page overflow so that it doesnt look scrunched up

**Comment by albertyee84** [comment]
Hey Carlos, here is the modal login/signup adjusted.!

![Screen Shot 2019-11-12 at 12 10 28 PM](https://user-images.githubusercontent.com/52211990/68706856-77dbd780-0545-11ea-8666-73de905c34c8.png)

**Comment by carlosaicrag** [comment]
awesome looks good.  the other thing I would say is to make the signup button a link thats a word. that way your errors have space to render on the bottom
